---
apiVersion: v1
kind: Namespace
metadata:
  name: platform

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: platform
type: Opaque
stringData:
  root-password: "change-me-in-production"
  db-user: "platform"
  db-password: "change-me-in-production"
